{"Id": "66992127", "PostTypeId": "1", "AcceptedAnswerId": "66996479", "CreationDate": "2021-04-07T18:31:54.620", "Score": "1", "ViewCount": "605", "Body": "<p>In an attempt to bring up a DynamoDb-triggered lambda, I'm constantly receiving this error:</p>\n<pre><code>Error: error creating Lambda Event Source Mapping (): ValidationException:\n        status code: 400, request id: 2e09272b-68e5-4713-b083-c95db9dbad6e\n\n  on dynamo.tf line 30, in resource &quot;aws_lambda_event_source_mapping&quot; &quot;dynamodb_lambda_mapping&quot;:\n  30: resource &quot;aws_lambda_event_source_mapping&quot; &quot;dynamodb_lambda_mapping&quot; {\n</code></pre>\n<p>And can't figure out what is it saying or how to debug it. That's the code:</p>\n<pre><code>resource &quot;aws_dynamodb_table&quot; &quot;connections_dynamodb_table&quot; {\nname           = &quot;tf-connections&quot;\nbilling_mode   = &quot;PROVISIONED&quot;\nhash_key       = &quot;connectionId&quot;\nread_capacity  = 5\nwrite_capacity = 5\n\nattribute {\n    name = &quot;connectionId&quot;\n    type = &quot;S&quot;\n}\n}\n\n\ndata &quot;archive_file&quot; &quot;dynamodb_triggered_lambda_code&quot; {\ntype        = &quot;zip&quot;\nsource_dir  = &quot;dynamodb_triggered_lambda_code&quot;\noutput_path = &quot;dynamodb_triggered_lambda_zipped_code.zip&quot;\n}\n\nresource &quot;aws_lambda_function&quot; &quot;dynamodb_triggered_lambda&quot; {\nfunction_name    = &quot;tf_test_dynamodb_triggered_lambda&quot;\nrole             = aws_iam_role.iam_for_lambda.arn\nhandler          = &quot;index.handler&quot;\nsource_code_hash = data.archive_file.dynamodb_triggered_lambda_code.output_base64sha256\nfilename         = &quot;dynamodb_triggered_lambda_zipped_code.zip&quot;\nruntime          = &quot;nodejs14.x&quot;\n}\n\nresource &quot;aws_lambda_event_source_mapping&quot; &quot;dynamodb_lambda_mapping&quot; {\nevent_source_arn  = aws_dynamodb_table.connections_dynamodb_table.stream_arn\nfunction_name     = aws_lambda_function.dynamodb_triggered_lambda.arn\nstarting_position = &quot;LATEST&quot;\n}\n</code></pre>\n<p>The <code>aws_iam_role.iam_for_lambda</code> resource is in another file in same directory. I ommitted it for sake of brevity..</p>\n", "OwnerUserId": "587467", "LastActivityDate": "2023-01-26T17:47:36.600", "Title": "ValidationException on aws_lambda_event_source_mapping", "Tags": "<terraform><terraform-provider-aws>", "AnswerCount": "2", "CommentCount": "0", "ContentLicense": "CC BY-SA 4.0", "history": [{"Id": "244207755", "PostHistoryTypeId": "2", "PostId": "66992127", "RevisionGUID": "654f1533-9ca5-4f9c-9bb2-c904514e83c0", "CreationDate": "2021-04-07T18:31:54.620", "UserId": "587467", "Text": "In an attempt to bring up a DynamoDb-triggered lambda, I'm constantly receiving this error:\r\n\r\n    Error: error creating Lambda Event Source Mapping (): ValidationException:\r\n            status code: 400, request id: 2e09272b-68e5-4713-b083-c95db9dbad6e\r\n    \r\n      on dynamo.tf line 30, in resource \"aws_lambda_event_source_mapping\" \"dynamodb_lambda_mapping\":\r\n      30: resource \"aws_lambda_event_source_mapping\" \"dynamodb_lambda_mapping\" {\r\n\r\nAnd can't figure out what is it saying or how to debug it. That's the code:\r\n\r\n    resource \"aws_dynamodb_table\" \"connections_dynamodb_table\" {\r\n    name           = \"tf-connections\"\r\n    billing_mode   = \"PROVISIONED\"\r\n    hash_key       = \"connectionId\"\r\n    read_capacity  = 5\r\n    write_capacity = 5\r\n\r\n    attribute {\r\n        name = \"connectionId\"\r\n        type = \"S\"\r\n    }\r\n    }\r\n\r\n\r\n    data \"archive_file\" \"dynamodb_triggered_lambda_code\" {\r\n    type        = \"zip\"\r\n    source_dir  = \"dynamodb_triggered_lambda_code\"\r\n    output_path = \"dynamodb_triggered_lambda_zipped_code.zip\"\r\n    }\r\n\r\n    resource \"aws_lambda_function\" \"dynamodb_triggered_lambda\" {\r\n    function_name    = \"tf_test_dynamodb_triggered_lambda\"\r\n    role             = aws_iam_role.iam_for_lambda.arn\r\n    handler          = \"index.handler\"\r\n    source_code_hash = data.archive_file.dynamodb_triggered_lambda_code.output_base64sha256\r\n    filename         = \"dynamodb_triggered_lambda_zipped_code.zip\"\r\n    runtime          = \"nodejs14.x\"\r\n    }\r\n\r\n    resource \"aws_lambda_event_source_mapping\" \"dynamodb_lambda_mapping\" {\r\n    event_source_arn  = aws_dynamodb_table.connections_dynamodb_table.stream_arn\r\n    function_name     = aws_lambda_function.dynamodb_triggered_lambda.arn\r\n    starting_position = \"LATEST\"\r\n    }\r\n\r\nThe `aws_iam_role.iam_for_lambda` resource is in another file in same directory. I ommitted it for sake of brevity..", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": [{"source": "Text", "text": "That's the code: resource \"aws_dynamodb_table\" \"connections_dynamodb_table\" { name = \"tf-connections\" billing_mode = \"PROVISIONED\" hash_key = \"connectionId\" read_capacity = 5 write_capacity = 5 attribute { name = \"connectionId\" type = \"S\" } } data \"archive_file\" \"dynamodb_triggered_lambda_code\" { type = \"zip\" source_dir = \"dynamodb_triggered_lambda_code\" output_path = \"dynamodb_triggered_lambda_zipped_code.zip\" } resource \"aws_lambda_function\" \"dynamodb_triggered_lambda\" { function_name = \"tf_test_dynamodb_triggered_lambda\" role = aws_iam_role.iam_for_lambda.arn handler = \"index.handler\" source_code_hash = data.archive_file.dynamodb_triggered_lambda_code.output_base64sha256 filename = \"dynamodb_triggered_lambda_zipped_code.zip\" runtime = \"nodejs14.x\" } resource \"aws_lambda_event_source_mapping\" \"dynamodb_lambda_mapping\" { event_source_arn = aws_dynamodb_table.connections_dynamodb_table.stream_arn function_name = aws_lambda_function.dynamodb_triggered_lambda.arn starting_position = \"LATEST\" ", "keywords": ["bill"]}]}, {"Id": "244207756", "PostHistoryTypeId": "1", "PostId": "66992127", "RevisionGUID": "654f1533-9ca5-4f9c-9bb2-c904514e83c0", "CreationDate": "2021-04-07T18:31:54.620", "UserId": "587467", "Text": "ValidationException on aws_lambda_event_source_mapping", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": []}, {"Id": "244207757", "PostHistoryTypeId": "3", "PostId": "66992127", "RevisionGUID": "654f1533-9ca5-4f9c-9bb2-c904514e83c0", "CreationDate": "2021-04-07T18:31:54.620", "UserId": "587467", "Text": "<terraform><terraform-provider-aws>", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": []}], "answers": [{"Id": "66996479", "PostTypeId": "2", "ParentId": "66992127", "CreationDate": "2021-04-08T02:16:39.623", "Score": "1", "Body": "<p>You have to <strong>enable streams</strong> for your table:</p>\n<pre><code>resource &quot;aws_dynamodb_table&quot; &quot;connections_dynamodb_table&quot; {\n  name           = &quot;tf-connections&quot;\n  billing_mode   = &quot;PROVISIONED&quot;\n  hash_key       = &quot;connectionId&quot;\n\n  stream_enabled = true\n  stream_view_type = &quot;NEW_AND_OLD_IMAGES&quot;\n\n  read_capacity  = 5\n  write_capacity = 5\n\n  attribute {\n      name = &quot;connectionId&quot;\n      type = &quot;S&quot;\n  }\n}\n\n</code></pre>\n", "OwnerUserId": "248823", "LastActivityDate": "2021-04-08T02:16:39.623", "CommentCount": "0", "ContentLicense": "CC BY-SA 4.0", "history": [{"Id": "244225773", "PostHistoryTypeId": "2", "PostId": "66996479", "RevisionGUID": "405d3fd3-d0ae-4f5b-9ba9-edaeefa62f01", "CreationDate": "2021-04-08T02:16:39.623", "UserId": "248823", "Text": "You have to **enable streams** for your table:\r\n\r\n```\r\nresource \"aws_dynamodb_table\" \"connections_dynamodb_table\" {\r\n  name           = \"tf-connections\"\r\n  billing_mode   = \"PROVISIONED\"\r\n  hash_key       = \"connectionId\"\r\n\r\n  stream_enabled = true\r\n  stream_view_type = \"NEW_AND_OLD_IMAGES\"\r\n\r\n  read_capacity  = 5\r\n  write_capacity = 5\r\n\r\n  attribute {\r\n      name = \"connectionId\"\r\n      type = \"S\"\r\n  }\r\n}\r\n\r\n```", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": [{"source": "Text", "text": "You have to **enable streams** for your table: ``` resource \"aws_dynamodb_table\" \"connections_dynamodb_table\" { name = \"tf-connections\" billing_mode = \"PROVISIONED\" hash_key = \"connectionId\" stream_enabled = true stream_view_type = \"NEW_AND_OLD_IMAGES\" read_capacity = 5 write_capacity = 5 attribute { name = \"connectionId\" type = \"S\" ", "keywords": ["bill"]}]}], "filtered-sentences": []}, {"Id": "75249855", "PostTypeId": "2", "ParentId": "66992127", "CreationDate": "2023-01-26T17:47:36.600", "Score": "0", "Body": "<p>I faced the exact same error message and error status code.\nIn my case, I was using the wrong lambda arn from the output of this terraform module: <a href=\"https://registry.terraform.io/modules/terraform-aws-modules/lambda/aws/latest\" rel=\"nofollow noreferrer\">https://registry.terraform.io/modules/terraform-aws-modules/lambda/aws/latest</a></p>\n<p>You should use the <code>lambda_function_arn</code> output from this module.</p>\n", "OwnerUserId": "9855588", "LastActivityDate": "2023-01-26T17:47:36.600", "CommentCount": "0", "ContentLicense": "CC BY-SA 4.0", "history": [{"Id": "286895692", "PostHistoryTypeId": "2", "PostId": "75249855", "RevisionGUID": "ee965c6a-04e0-473b-a45c-96dd8248d572", "CreationDate": "2023-01-26T17:47:36.600", "UserId": "9855588", "Text": "I faced the exact same error message and error status code.\r\nIn my case, I was using the wrong lambda arn from the output of this terraform module: https://registry.terraform.io/modules/terraform-aws-modules/lambda/aws/latest\r\n\r\nYou should use the `lambda_function_arn` output from this module.", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": []}], "filtered-sentences": []}], "contains-topic": true, "filtered-sentences": []}