{"Id": "76312758", "PostTypeId": "1", "CreationDate": "2023-05-23T08:34:59.423", "Score": "0", "ViewCount": "74", "Body": "<p>Investigating an issue with terraform applying i have found interesting behaviour (tf backend - s3):</p>\n<ol>\n<li>During terraform plan - we have output telling us resource (cur_report) was deleted out of terraform. AS part of plan - terraform plans to restore it.</li>\n</ol>\n<pre><code>\nTerraform detected the following changes made outside of Terraform since the last &quot;terraform apply&quot;:\n\n   aws_cur_report_definition.***[0] has been deleted\n - resource &quot;aws_cur_report_definition&quot; &quot;***&quot; {\n      - additional_schema_elements = [\n          - &quot;RESOURCES&quot;,\n        ] -&gt; null\n      - arn                        = &quot;arn:aws:cur:us-east-1:***:definition/***&quot; -&gt; null\n      - compression                = &quot;ZIP&quot; -&gt; null\n      - format                     = &quot;textORcsv&quot; -&gt; null\n      - id                         = &quot;***&quot; -&gt; null\n      - refresh_closed_reports     = true -&gt; null\n      - report_name                = &quot;***&quot; -&gt; null\n</code></pre>\n<ol start=\"2\">\n<li>Then while applying the generated plan - we receive an error &quot;Duplicated report name&quot; for this resource (which actually happens when report already exist). Report name is unique in scope of account. cur available in only 1  region.</li>\n</ol>\n<pre><code>error applying terraform: Error: error creating Cost And Usage Report Definition (***): DuplicateReportNameException\n</code></pre>\n<p>I have some ideas what could happen here:</p>\n<ol>\n<li>Maybe report actually was removed (we have additional not-direct proof for this) but somehow it was removed not completely and some trail remained in AWS that keeps marking report name is busy.</li>\n<li>Maybe something in AWS permissions was reconfigured in the way so our terraform just couldnt access report definition to check it exist (terraform applied by some role, not account owner)</li>\n<li>Some magic bug?</li>\n</ol>\n<p>And it is not 1-time issue, it keeps working that way for this exact account.</p>\n<p>Please share your ideas or knowledges on what could happen here (or maybe what surely did not happen here)</p>\n", "OwnerUserId": "6160821", "LastActivityDate": "2023-05-23T08:34:59.423", "Title": "Terraform did not find resource during tf plan, and then failed to create it with \"Duplicated\" error", "Tags": "<amazon-web-services><terraform>", "AnswerCount": "0", "CommentCount": "5", "ContentLicense": "CC BY-SA 4.0", "comments": [{"Id": "134570692", "PostId": "76312758", "Score": "0", "Text": "Does the report actually show up in the AWS console? Then it might be a terraform issue. If the report does not show up in AWS but you still cannot recreate it then it is an AWS issues and you should contact their support.", "CreationDate": "2023-05-23T08:37:56.557", "UserId": "2442804", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": []}, {"Id": "134570752", "PostId": "76312758", "Score": "0", "Text": "That is the problem - we have no direct access to the account, it is only secretly-chain-assumed role as part of application.", "CreationDate": "2023-05-23T08:42:14.030", "UserId": "6160821", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": []}, {"Id": "134570767", "PostId": "76312758", "Score": "0", "Text": "Then you really need to get in touch with however has proper access. Debugging these issues from afar is basically impossible.", "CreationDate": "2023-05-23T08:43:11.963", "UserId": "2442804", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": []}, {"Id": "134570791", "PostId": "76312758", "Score": "0", "Text": "Just was expecting maybe it is already some known bug", "CreationDate": "2023-05-23T08:45:27.713", "UserId": "6160821", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": []}, {"Id": "134574031", "PostId": "76312758", "Score": "1", "Text": "It is possible the AWS provider is setting state ID for this resource with something other than the report name, and this would indicate the resource does not exist. Then the attempted `Create` fails because another report possesses the same name, and therefore fails one of the AWS API uniqueness validations. That would also be a bug to report to the AWS provider if that is true however.", "CreationDate": "2023-05-23T12:32:50.733", "UserId": "5343387", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": [{"source": "Text", "text": "It is possible the AWS provider is setting state ID for this resource with something other than the report name, and this would indicate the resource does not exist. ", "keywords": ["provider"]}, {"source": "Text", "text": "That would also be a bug to report to the AWS provider if that is true however.", "keywords": ["provider"]}]}], "history": [{"Id": "293175928", "PostHistoryTypeId": "2", "PostId": "76312758", "RevisionGUID": "de25bd6c-7daf-4953-980d-dfb2e6a7cbab", "CreationDate": "2023-05-23T08:34:59.423", "UserId": "6160821", "Text": "Investigating an issue with terraform applying i have found interesting behaviour (tf backend - s3): \r\n1) During terraform plan - we have output telling us resource (cur_report) was deleted out of terraform. AS part of plan - terraform plans to restore it.\r\n\r\n```Note: Objects have changed outside of Terraform\r\n\r\nTerraform detected the following changes made outside of Terraform since the last \"terraform apply\":\r\n\r\n   aws_cur_report_definition.***[0] has been deleted\r\n - resource \"aws_cur_report_definition\" \"***\" {\r\n      - additional_schema_elements = [\r\n          - \"RESOURCES\",\r\n        ] -> null\r\n      - arn                        = \"arn:aws:cur:us-east-1:***:definition/***\" -> null\r\n      - compression                = \"ZIP\" -> null\r\n      - format                     = \"textORcsv\" -> null\r\n      - id                         = \"***\" -> null\r\n      - refresh_closed_reports     = true -> null\r\n      - report_name                = \"***\" -> null\r\n```\r\n 2. Then while applying the generated plan - we receive an error \"Duplicated report name\" for this resource (which actually happens when report already exist). Report name is unique in scope of account. cur available in only 1  region.\r\n\r\n```\r\nerror applying terraform: Error: error creating Cost And Usage Report Definition (***): DuplicateReportNameException\r\n```\r\n\r\nI have some ideas what could happen here:\r\n1) Maybe report actually was removed (we have additional not-direct proof for this) but somehow it was removed not completely and some trail remained in AWS that keeps marking report name is busy.\r\n2) Maybe something in AWS permissions was reconfigured in the way so our terraform just couldnt access report definition to check it exist (terraform applied by some role, not account owner)\r\n3) Some magic bug?\r\n\r\nAnd it is not 1-time issue, it keeps working that way for this exact account. \r\n\r\nPlease share your ideas or knowledges on what could happen here (or maybe what surely did not happen here)", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": [{"source": "Text", "text": "```Note: Objects have changed outside of Terraform Terraform detected the following changes made outside of Terraform since the last \"terraform apply\": aws_cur_report_definition.***[0] has been deleted - resource \"aws_cur_report_definition\" \"***\" { - additional_schema_elements = [ - \"RESOURCES\", ] -> null - arn = \"arn:aws:cur:us-east-1:***:definition/***\" -> null - compression = \"ZIP\" -> null - format = \"textORcsv\" -> null - id = \"***\" -> null - refresh_closed_reports = true -> null - report_name = \"***\" -> null ``` ", "keywords": ["change"]}, {"source": "Text", "text": "``` error applying terraform: Error: error creating Cost And Usage Report Definition (***): DuplicateReportNameException ``` ", "keywords": ["cost"]}]}, {"Id": "293175930", "PostHistoryTypeId": "1", "PostId": "76312758", "RevisionGUID": "de25bd6c-7daf-4953-980d-dfb2e6a7cbab", "CreationDate": "2023-05-23T08:34:59.423", "UserId": "6160821", "Text": "Terraform did not find resource during tf plan, and then failed to create it with \"Duplicated\" error", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": []}, {"Id": "293175931", "PostHistoryTypeId": "3", "PostId": "76312758", "RevisionGUID": "de25bd6c-7daf-4953-980d-dfb2e6a7cbab", "CreationDate": "2023-05-23T08:34:59.423", "UserId": "6160821", "Text": "<amazon-web-services><terraform>", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": []}], "contains-topic": true, "filtered-sentences": []}